### ISSUE TITLE
Link to buy a commercial license is broken

### ISSUE THREAD

**Issue by 1Maxnet1** [public-transport/gtfs-via-postgres#29]
In the Readme.md there is the possibility mentioned to buy commercial licenses. I wanted to have a look at the offerings, but wasn't able to do so, as the [current link](https://licensezero.com/offers/b93ed685-e6f5-45e6-a120-d99b46f30bf2) just leads me to [this website](https://artlessdevices.com/) which is a collection of links to explanations of different licenses.

Could you check the link?

Regards

Maxnet

**Comment by derhuerst** [comment]
Thank you for bringing this to my attention.

A while ago, when I put the link into the readme, the License Zero page offered the option to buy a license for `gtfs-via-postgres` online. But it seems like [Kyle E. Mitchell](https://kemitchell.com/) has moved on to [a new project](https://fastpathlicense.com).

I think I'll just change the readme to something with a lot more friction: Asking me for a commercial license via email.
