### ISSUE TITLE
Docker Image Missing

### ISSUE THREAD

**Issue by langbein-daniel** [public-transport/gtfs-via-postgres#41]
Hi, many thanks for developing this project!

---

When following the link in the README to the provided Docker image, there is a 404 page from GitHub: https://github.com/public-transport/gtfs-via-postgres/pkgs/container/gtfs-via-postgres

Furthermore, I can't pull it with Docker: `docker pull ghcr.io/public-transport/gtfs-via-postgres`:

```
Error response from daemon: Head "https://ghcr.io/v2/public-transport/gtfs-via-postgres/manifests/latest": denied
```

**Comment by derhuerst** [comment]
This is because the following CI runs have all failed:

- https://github.com/public-transport/gtfs-via-postgres/actions/runs/4558514655
- https://github.com/public-transport/gtfs-via-postgres/actions/runs/4693748935
- https://github.com/public-transport/gtfs-via-postgres/actions/runs/5027793076

**Comment by derhuerst** [comment]
I have uploaded binaries manually to the `gtfs-via-postgres@4.6.0` & `gtfs-via-postgres@4.7.0` releases.

**Comment by derhuerst** [comment]
There also is a [legacy Docker Hub repository `docker.io/publictransport/gtfs-via-postgres`](https://hub.docker.com/repository/docker/publictransport/gtfs-via-postgres/general), which contains images up to `4.5.1`.

**Comment by derhuerst** [comment]
I have also pushed the `ghcr.io/public-transport/gtfs-via-postgres:latest` & `ghcr.io/public-transport/gtfs-via-postgres:4` images to the GitHub Container Registry referenced in the docs.

**Comment by derhuerst** [comment]
I'll close this, given that the images are publicly available now.

The only leftover task: Getting the CI to run through again.

**Comment by langfingaz** [comment]
Many thanks for pushing the images manually and good luck with fixing the CI pipeline.
