### ISSUE TITLE
Multiple GTFS for one db error

### ISSUE THREAD

**Issue by mnai01** [public-transport/gtfs-via-postgres#52]
When trying to import multiple GTFS feeds I get "relation shapes already exist?

```sh
is_valid_lang_code
is_timezone
NOTIshapes
CE:  extension "postgis" already exists, skipping
CREATE EXTENSION
BEGIN
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
CREATE FUNCTION
COMMENT
ERROR:  relation "shapes" already exists
STATEMENT:  CREATE TABLE "public".shapes (
        id SERIAL PRIMARY KEY,
        shape_id TEXT,
        shape_pt_sequence INT,
        shape_pt_loc geography(POINT),
        shape_dist_traveled REAL
);
```

Maybe this is on my end and I shouldn't be adding multiple GTFS feeds to the same tables? However, I thought this was a normal design protocol for handling GTFS static data. The only option to fix this while using the current version of `gtfs-via-postgres` would be to have unique DBs for each GTFS, which doesn't seem practical when there are multiple GTFS feeds for a single transit agency. Any recommendations?

**Comment by danthonywalker** [comment]
See #51 as it seems related

**Comment by mnai01** [comment]
Closing issue as #51 discusses problem in furthermore details

**Comment by mnai01** [comment]
Closing issue as #51  discusses problem in furthermore details

**Comment by mnai01** [comment]
Closing issue as #51 discusses the problem in furthermore details
